# Sunton ESP32-S3-8048S070 480px X 800px Smart Screen
# Hardware configuration file

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  min_version: 2024.7.0  
  project:
    name: "${project_name}"
    version: "${project_version}"    
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_build.flash_size: 16MB
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "/config/esphome/custom_partitions_3584.csv"
    
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
# Required to achieve sufficient PSRAM bandwidth
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y    
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

preferences:
  flash_write_interval: 1min      

#-------------------------------------------
#  Audio output (Mono)
#-------------------------------------------

# Not working on framework type: esp-idf

#i2s_audio:
#  i2s_lrclk_pin: 18
#  i2s_bclk_pin: 19

#media_player:
#  - platform: i2s_audio
#    name: ${friendly_name}
#    dac_type: external
#    i2s_dout_pin: 17
#    mode: stereo
#    id: media_out   

#-------------------------------------------
# Backlight
#-------------------------------------------
output:
  - platform: ledc
    pin: 10
    frequency: 1000
    id: gpio_backlight_pwm

light:
  - platform: monochromatic # Define a monochromatic, dimmable light for the backlight
    output: gpio_backlight_pwm
    name: Display Backlight
    id: back_light
    brightness: 0.8
    restore_mode: ALWAYS_ON

#-------------------------------------------
# Touchscreen gt911 i2c
#-------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO17
    scl: GPIO18
    
touchscreen:
  platform: gt911
  transform:
    mirror_x: false
    mirror_y: false
  id: my_touchscreen
  display: my_display

  on_touch:
    - logger.log:
          format: Touch at (%d, %d)
          args: [touch.x, touch.y]
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

#-------------------------------------------
# Display EK9716
#-------------------------------------------
display:
  - platform: rpi_dpi_rgb
    id: my_display
    color_order: RGB
    invert_colors: True
    update_interval: 2s
    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    rotation: 0
    dimensions:
      width: 1024 
      height: 600
    de_pin: 40
    hsync_pin: 39
    vsync_pin: 41
    pclk_pin: 42
    pclk_frequency: 16000000
    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 128
    vsync_front_porch: 13
    vsync_pulse_width: 3
    vsync_back_porch: 45


    data_pins:
      red:
        - 45        #r0
        - 48        #r1
        - 47        #r2
        - 21        #r3
        - 14        #r4
      green:
        - 5       #g0
        - 6       #g1
        - 7       #g2
        - 15      #g3
        - 16      #g4
        - 4       #g5
      blue:
        - 8        #b0
        - 3        #b1
        - 46       #b2
        - 9        #b3
        - 1        #b4